<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [All Test Suite]" guice-stage="DEVELOPMENT">
  <test thread-count="5" name="TestVerifiesThatErrorMessage177(failed)">
    <groups>
      <run>
        <include name="regression"/>
      </run>
    </groups>
    <classes>
      <class name="com.ita.speakukrainian.ui.tests.TestVerifiesThatErrorMessage177">
        <methods>
          <include name="TestVerifiesTheErrorMessageWhenEnter1501Symbols" invocation-numbers="0"/>
          <include name="TestVerifiesTheErrorMessageWhenEnterMore1500Symbols" invocation-numbers="0"/>
          <include name="TestVerifiesTheErrorMessageWhenEnterMore1500Symbols2" invocation-numbers="0"/>
          <include name="TestVerifiesTheErrorMessageWhenEnter1500Symbols" invocation-numbers="0"/>
          <include name="TestVerifiesTheErrorMessageWhenEnter1501Symbols2" invocation-numbers="0"/>
          <include name="TestVerifiesTheErrorMessageWhenEnterLess1500Symbols" invocation-numbers="0"/>
        </methods>
      </class> <!-- com.ita.speakukrainian.ui.tests.TestVerifiesThatErrorMessage177 -->
    </classes>
  </test> <!-- TestVerifiesThatErrorMessage177(failed) -->
</suite> <!-- Failed suite [All Test Suite] -->
